### ISSUE TITLE
Code to predict and evaluate the model for task 1?

### ISSUE THREAD

**Issue by cuongngm** [zzzDavid/ICDAR-2019-SROIE#16]
I am training CTPN model in pytorch based your task 1 code, it is clear and help me more understand the original paper . But i see 2 problem. 
-First, when i trained with SROIE 2019 dataset by your code,  i met with "cuda out of memory" after first epoch, and my solution is add  "with torch.no_grad()" in line 64 of file "train.py". 
-Second, i trained your code with 10 epochs and loss values don't converge. After,  i changed the optimizer from "adagrad" to "SGD" with lr=1e-3. And this work.
Hope this help anyone.

I had the weights of model and i have a question for author. Can you share the code to predict and evaluate the model? Tks

**Comment by patrick22414** [comment]
Hi! Thank you for the interest and help. I'm glad that the code has helped you.

I'm really sorry to say that I cannot give you the predict/eval code because I haven't written them. I must admit I have half-abandoned the revamp since my work got busy.

If you would like to add your own predict/eval code, you could submit a pull request and I'll be sure to check it out. I believe I left it around NMS and visualisation.

Again, I appreciate your effort and I'm sorry that I cannot give you a satisfactory answer.

**Comment by cuongngm** [comment]
Tks for your reply. I will attempt. Wish you all the best in your work.

Vào Th 5, 3 thg 12, 2020 vào lúc 22:22 Patrick Yang <
notifications@github.com> đã viết:
